version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: better-sqlite3
    versions:
    - 7.1.2
    - 7.1.4
  - dependency-name: random-meow
    versions:
    - 3.9.0
  - dependency-name: opusscript
    versions:
    - 0.0.7
  - dependency-name: canvas
    versions:
    - 2.6.1
